WITH BASE AS (
    SELECT 
        CC.SERVICE_CENTER,
        CC.SERVICE_CENTER_ID,
        CC.ID AS C_ID,
        CC.SERVICE_NO,
        CC.COMPLAIN_TYPE,
        CC.BARCODE,
        CC.CREATED_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY CC.BARCODE 
            ORDER BY CC.CREATED_DATE
        ) AS VISIT_NO
    FROM CRM.CUSTOMER_COMPLAINS CC
    WHERE CC.ALKP_COMPLAIN_LEVEL_ID IN (22,25,26,27,28,29)        
        AND CC.SERVICE_CENTER_ID IS NOT NULL
        AND CC.SERVICE_CENTER_ID IN (
            SELECT O.HRMS_ORGID
            FROM CRM.ORG_MAP O
            WHERE O.HRMS_ORGID = CC.SERVICE_CENTER_ID
                  
            AND O.IS_ACTIVE = 1
            AND O.IS_LIVE <> 0
            AND O.COUNTRY IS NULL
            AND O.HRMS_ORGID <> 563
        
        )
        AND NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER','LONG_TIME_UNDELIVERED')
        AND NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER','LONG_TIME_UNDELIVERED')
        AND CC.PRODUCT_GROUP = NVL('FRIDGE', CC.PRODUCT_GROUP)
        AND CC.SERVICE_CENTER_ID = NVL('72776359', CC.SERVICE_CENTER_ID)
        AND TRUNC (CC.CREATED_DATE) BETWEEN '01-NOV-2025'
                                        AND '25-NOV-2025'
)
SELECT 
    SERVICE_CENTER,
    SERVICE_CENTER_ID,
    COUNT(CASE WHEN VISIT_NO = 1 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS FIRST_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 2 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS SECOND_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 3 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS THIRD_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 4 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS FOURTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 5 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS FIFTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 6 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS SIXTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 7 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS SEVENTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 8 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS EIGHTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO = 9 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS NINTH_TIME_INDOOR,
    COUNT(CASE WHEN VISIT_NO >= 10 AND COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS TENTH_ABOVE_TIME_INDOOR,
    
    COUNT(CASE WHEN VISIT_NO = 1 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS FIRST_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 2 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS SECOND_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 3 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS THIRD_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 4 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS FOURTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 5 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS FIFTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 6 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS SIXTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 7 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS SEVENTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 8 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS EIGHTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO = 9 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS NINTH_TIME_OUTDOOR,
    COUNT(CASE WHEN VISIT_NO >= 10 AND COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS TENTH_ABOVE_TIME_OUTDOOR,


    COUNT(CASE WHEN COMPLAIN_TYPE = 'INDOOR' THEN 1 END) AS TOTAL_INDOOR,
    COUNT(CASE WHEN COMPLAIN_TYPE = 'OUTDOOR' THEN 1 END) AS TOTAL_OUTDOOR
FROM BASE
GROUP BY 
    SERVICE_CENTER,
    SERVICE_CENTER_ID
ORDER BY SERVICE_CENTER