WITH ORG_ACTIVE AS (
SELECT
	/*+ INDEX(O IDX_ORG_ACTIVE) */
	HRMS_ORGID,
	HRMS_ORG_TITLE
FROM
	CRM.ORG_MAP O
WHERE
	O.IS_ACTIVE = 1
	AND O.IS_LIVE <> 0
	AND O.COUNTRY IS NULL
	AND O.HRMS_ORGID <> 563
        
),

/* ===========================
   DELIVERY PENDING (TOTAL)
   =========================== */
DELIVERY_PENDING_CTE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS DELIVERY_PENDING,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID = 26
		AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
	GROUP BY
		CC.SERVICE_CENTER_ID,
		O.HRMS_ORG_TITLE
),

/* ===========================
   DELIVERY PENDING (DATE-WISE)
   =========================== */
DELIVERY_PENDING_CTE_DATE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS DELIVERY_PENDING,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID = 26
		AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
			AND TRUNC(CC.CREATED_DATE) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
		GROUP BY
			CC.SERVICE_CENTER_ID,
			O.HRMS_ORG_TITLE
),

/* ===========================
   RECEIVED CTE
   =========================== */
RECEIVED_CTE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS RECEIVED,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID IN (22, 25, 26, 27, 28, 29)
			AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
				AND TRUNC(CC.CREATED_DATE) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
			GROUP BY
				CC.SERVICE_CENTER_ID,
				O.HRMS_ORG_TITLE
),

/* ===========================
   WORK DONE (TOTAL)
   =========================== */
WORK_DONE_CTE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS WORK_DONE,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
JOIN CRM.JOBS J ON
	J.CUST_COMPLAIN_ID = CC.ID
	AND J.ID = (
	SELECT
		MAX(ID)
	FROM
		CRM.JOBS
	WHERE
		CUST_COMPLAIN_ID = CC.ID)
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID IN (26, 27)
			AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
				AND TRUNC(NVL(J.QC_END_DATE, J.QC_START_DATE)) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
			GROUP BY
				CC.SERVICE_CENTER_ID,
				O.HRMS_ORG_TITLE
),

/* ===========================
   WORK DONE (DATE-WISE)
   =========================== */
WORK_DONE_CTE_DATE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS WORK_DONE,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
JOIN CRM.JOBS J ON
	J.CUST_COMPLAIN_ID = CC.ID
	AND J.ID = (
	SELECT
		MAX(ID)
	FROM
		CRM.JOBS
	WHERE
		CUST_COMPLAIN_ID = CC.ID)
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID IN (26, 27)
			AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
				AND TRUNC(NVL(J.QC_END_DATE, J.QC_START_DATE)) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
					AND TRUNC(CC.CREATED_DATE) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
				GROUP BY
					CC.SERVICE_CENTER_ID,
					O.HRMS_ORG_TITLE
),

/* ===========================
   WORK PENDING (TOTAL)
   =========================== */
WORK_PENDING_CTE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS WORK_PENDING,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
LEFT JOIN CRM.JOBS J ON
	J.CUST_COMPLAIN_ID = CC.ID
	AND J.ID = (
	SELECT
		MAX(ID)
	FROM
		CRM.JOBS
	WHERE
		CUST_COMPLAIN_ID = CC.ID)
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID = 25
		AND NVL(J.ALKP_JOB_STATUS_ID, 0) IN (1316, 24, 41, 42)
			AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
		GROUP BY
			CC.SERVICE_CENTER_ID,
			O.HRMS_ORG_TITLE
),

/* ===========================
   WORK PENDING (DATE-WISE)
   =========================== */
WORK_PENDING_CTE_DATE AS (
SELECT
	CC.SERVICE_CENTER_ID,
	O.HRMS_ORG_TITLE AS TITLE,
	COUNT(*) AS WORK_PENDING,
	ROW_NUMBER() OVER (
	ORDER BY COUNT(*) ASC) AS RN
FROM
	CRM.CUSTOMER_COMPLAINS CC
JOIN ORG_ACTIVE O ON
	O.HRMS_ORGID = CC.SERVICE_CENTER_ID
LEFT JOIN CRM.JOBS J ON
	J.CUST_COMPLAIN_ID = CC.ID
	AND J.ID = (
	SELECT
		MAX(ID)
	FROM
		CRM.JOBS
	WHERE
		CUST_COMPLAIN_ID = CC.ID)
WHERE
	NVL(CC.TRANSFER_TYPE, 0) NOT IN ('REPLACEMENT_TRANSFER', 'LONG_TIME_UNDELIVERED')
		AND CC.ALKP_COMPLAIN_LEVEL_ID = 25
		AND NVL(J.ALKP_JOB_STATUS_ID, 0) IN (1316, 24, 41, 42)
			AND CC.PRODUCT_GROUP = NVL('', CC.PRODUCT_GROUP)
				AND TRUNC(CC.CREATED_DATE) BETWEEN '01-NOV-2025' AND '19-NOV-2025'
			GROUP BY
				CC.SERVICE_CENTER_ID,
				O.HRMS_ORG_TITLE
)

SELECT
	/* DELIVERY PENDING */
	DP.TITLE AS DELIVERY_PENDING_TITLE,
	DP.DELIVERY_PENDING AS DELIVERY_PENDING_TOTAL,
	DP_DATE.DELIVERY_PENDING AS DELIVERY_PENDING_DATE_WISE,
	NVL(RC_DEL.RECEIVED, 0) AS DELIVERY_PENDING_RECEIVED_QTY,
	/* RECEIVED */
	RC.TITLE AS RECEIVED_TITLE,
	RC.RECEIVED AS RECEIVED_TOTAL,
	/* WORK DONE */
	WD.TITLE AS WORK_DONE_TITLE,
	WD.WORK_DONE AS WORK_DONE_TOTAL,
	WD_DATE.WORK_DONE AS WORK_DONE_DATE_WISE,
	NVL(RC_WD.RECEIVED, 0) AS WORK_DONE_RECEIVED_QTY,
	/* WORK PENDING */
	WP.TITLE AS WORK_PENDING_TITLE,
	WP.WORK_PENDING AS WORK_PENDING_TOTAL,
	WP_DATE.WORK_PENDING AS WORK_PENDING_DATE_WISE,
	NVL(RC_WP.RECEIVED, 0) AS WORK_PENDING_RECEIVED_QTY
FROM
	DELIVERY_PENDING_CTE DP
LEFT JOIN DELIVERY_PENDING_CTE_DATE DP_DATE
       ON
	DP.SERVICE_CENTER_ID = DP_DATE.SERVICE_CENTER_ID
LEFT JOIN RECEIVED_CTE RC_DEL
       ON
	DP.SERVICE_CENTER_ID = RC_DEL.SERVICE_CENTER_ID
LEFT JOIN RECEIVED_CTE RC
       ON
	RC.RN = DP.RN
	AND RC.RN <= 10
LEFT JOIN WORK_DONE_CTE WD
       ON
	DP.RN = WD.RN
LEFT JOIN WORK_DONE_CTE_DATE WD_DATE
       ON
	WD.SERVICE_CENTER_ID = WD_DATE.SERVICE_CENTER_ID
LEFT JOIN RECEIVED_CTE RC_WD
       ON
	WD.SERVICE_CENTER_ID = RC_WD.SERVICE_CENTER_ID
LEFT JOIN WORK_PENDING_CTE WP
       ON
	DP.RN = WP.RN
LEFT JOIN WORK_PENDING_CTE_DATE WP_DATE
       ON
	WP.SERVICE_CENTER_ID = WP_DATE.SERVICE_CENTER_ID
LEFT JOIN RECEIVED_CTE RC_WP
       ON
	WP.SERVICE_CENTER_ID = RC_WP.SERVICE_CENTER_ID
WHERE
	DP.RN <= 10
ORDER BY
	DP.RN